# Generated by Django 5.1 on 2024-10-26 15:19

import django.db.models.deletion
import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_tech_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Status')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='history',
            field=models.ManyToManyField(to='tickets.history'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(blank=True, default=tickets.models.get_default_status_id, null=True, on_delete=django.db.models.deletion.RESTRICT, to='tickets.status'),
        ),
    ]
